defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: 子どものためのプログラミング道場
subtitle: CoderDojo 立川
avatar: ../assets/images/1.jpg
github:
  owner_gravatar_url: https://github.com/CoderDojoTachikawa

# Side Menu Links
menu:
  - text: トップ
    link: /
    icon: ""

  - text: はじめての方へ
    link: /first
    icon: ""

  - text: CoderDojo について
    link: /skills-and-offers
    icon: ""

  - text: ブログ（開催の様子）
    link: https://coderdojotachikawa.tamaliver.jp/
    icon: ""

  - text: メンバー紹介
    link: /member
    icon: ""

  - text: スタッフメンバー募集（ボランティア）
    link: https://activo.jp/articles/72556
    icon: ""

  - text: ご支援、ご協力のお願い（会計報告）
    link: /contact
    icon: ""

  - text: お問い合わせ
    link: https://coderdojotachikawa.tamaliver.jp/blogmessage
    icon: ""


# Socialmedia Icons
social_icons:
#  - name: facebook
#    link: https://www.facebook.com/CoderDojoTachikawa
#    icon: fab fa-facebook-square

  - name: twitter
    link: https://twitter.com/CoderDojoTckw
    icon: fab fa-twitter

# Google Analytics
google_analytics: UA-109369485-1

